import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import DeviceDetector from "device-detector-js"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function download() {
    if (typeof window != "undefined") {
      try {
        const detector = new DeviceDetector()
        const device = detector.parse(window.navigator.userAgent)

        const platform = device.os?.name.toLowerCase()

        const res = await fetch(`/api/latest/${platform}`)
        const data = await res.json()

        if (res.status == 200) {
          const a = document.createElement("a")

          a.href = data.url
          a.download = data.name
          document.body.appendChild(a)
          a.click()
          document.body.removeChild(a)
        }
      } catch (err) {
        console.log(err)
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        </div>

        <div className={styles.center}>
          <div className="flex flex-col items-center justify-center gap-5">
            <div className="text-6xl text-white uppercase font-bold tracking-widest">
              Credo
            </div>
            <div className="text-lg opacity-60">
              Invoicing App
            </div>
          </div>
        </div>

        <div className={styles.grid}>
          <button
            className={styles.card}
            onClick={download}
          >
            <h2 className="text-2xl">
              Download Latest Version
            </h2>
            <p className={inter.className}>
              Download App for your platform
            </p>
          </button>
        </div>
      </main>
    </>
  )
}
